### PR TITLE
Add support for batch conversion and file-type verification

### PR DESCRIPTION
**Pull request by clauswilke**
Two much needed features.

### CODE REVIEW

**Comment by clauswilke** [comment]
I added a third feature: set the modification date of the converted file correctly.

**Review by andrewkern — COMMENTED** [review]
gonna have to change the readme!

**Comment by clauswilke** [comment]
Ah yes, documentation. The current readme is not wrong, it just needs expanding.

**Comment by clauswilke** [comment]
Ups, wasn't true. The readme made a statement about time stamps. Will prepare new pull request now.

**Pull request merged**
